markw: qcom-caf/media: correct misleading indention
* device/xiaomi/mido/qcom-caf/media/mm-video-v4l2/vidc/venc/src/omx_video_encoder.cpp:1651:21: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                    m_sHierLayers.nNumLayers = pParam->nNumLayers;

(cherry picked from commit fb01ab943b050f8484b5576cc4db97bd3dfbae33)