markw: qcom-caf/audio: fix duplicated conversion
* device/xiaomi/mido/qcom-caf/audio/mm-audio/aenc-evrc/qdsp6/src/omx_evrc_aenc.cpp:471:74: error: more '%' conversions than data arguments [-Werror,-Wformat-insufficient-args]
        DEBUG_DETAIL("EBD CB:: in_buf_len=%d nNumInputBuf=%d %d ebd_cnt %d \n",\

(cherry picked from commit ec70dd4027e395bf1236a70d7345f597b73c33e0)